favicon: null
name: Our Frictionless Society
opengraph:
  image: null
  type: null
  appId: null
collections:
  - index:
      path: /
      number: 15
      paginate: true
      navigable: true
    permalink:
      path: '/:title/'
    feed:
      path: /rss.xml
      format: rss
      number: 10
purpose: []
color:
  saturation: 0.8377193
  brandStrength: 0.25
  lightness: 0.4987469
  brandColors:
    - '#3e854d'
    - '#73562d'
    - '#2b1b07'
    - '#e8eae7'
    - '#b1b5ab'
  rhythmicContrast: 0.4611529
typography_spectrum: 0.3464912
layout_spectrum: 0.1779449
analytics:
  twitter: null
  google: null
  facebook: null
cta:
  bucket: null
  version: null
  domain: null
